version: '3.8'
services:
    db:
        image: mysql:8.0
        container_name: mydatabase
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: myphpmyadmin
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 512M
    web:
        build: ./
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
        depends_on:
            - db
